export const TARGETS_META = [
  { id:'SRV-001', hostname:'apolo',               apps:['Sistema Juzgados Turno'],           authorizedUsers:['Juzgados de Turno','SGTIC'] },
  { id:'SRV-002', hostname:'dav',                 apps:['DAV'],                              authorizedUsers:['SGTIC'] },
  { id:'SRV-003', hostname:'emision-antecedentes',apps:['Emisión Antecedentes','Citripio'],  authorizedUsers:['SGTIC'] },
  { id:'SRV-004', hostname:'gestion-usuarios',    apps:['Gestión de Usuarios','LDAP'],       authorizedUsers:['SGTIC'] },
  { id:'SRV-005', hostname:'escritorio-policial', apps:['Escritorio Policial'],              authorizedUsers:['SGP','SGTIC'] },
  { id:'SRV-006', hostname:'expertaje-citas',     apps:['Citas Expertajes'],                 authorizedUsers:['Expertaje-SGIC','SGTIC'] },
  { id:'SRV-007', hostname:'flota-vehicular',     apps:['Flota Vehicular'],                  authorizedUsers:['SGAL','SGTIC'] },
  { id:'SRV-008', hostname:'gestor-documental',   apps:['Gestor Documental'],                authorizedUsers:['SGED','SGTIC'] },
  { id:'SRV-009', hostname:'monitor-infra',       apps:['Zabbix','Grafana'],                 authorizedUsers:['SGTIC'] },
  { id:'SRV-010', hostname:'ldap-directorio',     apps:['LDAP Directorio Activo'],           authorizedUsers:['SGTIC'] },
  { id:'SRV-011', hostname:'novedades',           apps:['Sistema Novedades','Línea 110'],    authorizedUsers:['SGO-110','SGTIC'] },
  { id:'SRV-012', hostname:'orca',                apps:['ORCA'],                             authorizedUsers:['SGIC','SGTIC'] },
  { id:'SRV-013', hostname:'osticket',            apps:['OSTicket','Helpdesk'],              authorizedUsers:['SGTIC'] },
  { id:'SRV-014', hostname:'antecedentes-linea',  apps:['Antecedentes en Línea'],            authorizedUsers:['PNC'] },
  { id:'SRV-015', hostname:'rvr',                 apps:['RVR Vehículos Robados'],            authorizedUsers:['Rvr-SGIC','SGTIC'] },
  { id:'SRV-016', hostname:'sae',                 apps:['SAE Armas y Explosivos'],           authorizedUsers:['Didade-SGIC','SGTIC'] },
  { id:'SRV-017', hostname:'sapo-g',              apps:['SAPO-G Antecedentes'],              authorizedUsers:['Gacri-SGIC','SGTIC'] },
  { id:'SRV-018', hostname:'siav-app',            apps:['SIAV Atención Víctima'],            authorizedUsers:['Oav-SGO','SGTIC'] },
  { id:'SRV-019', hostname:'sispe-app',           apps:['SISPE App'],                        authorizedUsers:['PNC'] },
  { id:'SRV-020', hostname:'gitlab',              apps:['GitLab CE'],                        authorizedUsers:['SGTIC'] },
  { id:'SRV-021', hostname:'ws-api-consultas',    apps:['ws-api-consultas'],                 authorizedUsers:['RAP','SGSP','SGTIC'] },
  { id:'SRV-022', hostname:'ws-autentica',        apps:['ws-autentica'],                     authorizedUsers:['SGTIC'] },
  { id:'SRV-023', hostname:'ws-bancos',           apps:['ws-bancos'],                        authorizedUsers:['SGTIC','Bancos'] },
  { id:'SRV-024', hostname:'ws-renap',            apps:['WsRenap'],                          authorizedUsers:['SGTIC'] },
  { id:'SRV-025', hostname:'bd-principal',        apps:['MySQL','PostgreSQL RVR/SIAV'],      authorizedUsers:['SGTIC'] },
  { id:'SRV-026', hostname:'bd-autentica',        apps:['bd-autentica'],                     authorizedUsers:['SGTIC'] },
  { id:'SRV-027', hostname:'bd-logs',             apps:['MySQL logs'],                       authorizedUsers:['SGTIC'] },
  { id:'SRV-028', hostname:'bd-sapo',             apps:['bd-sapo'],                          authorizedUsers:['SGTIC'] },
  { id:'SRV-029', hostname:'bd-sispe-oracle',     apps:['Oracle DB SISPE'],                  authorizedUsers:['DG/IG'] },
  { id:'SRV-030', hostname:'bd-policiales',       apps:['bd-policiales'],                    authorizedUsers:['SGTIC'] },
  { id:'SRV-031', hostname:'bd-flota-vehicular',  apps:['Bd-FlotaV'],                        authorizedUsers:['SGTIC'] },
  { id:'SRV-032', hostname:'bd-sae',              apps:['Bd-sae'],                           authorizedUsers:['SGTIC'] },
  { id:'SRV-033', hostname:'dmz-publico',         apps:['sistemas.pnc.gob.gt'],              authorizedUsers:['NACIONAL'] },
  { id:'SRV-034', hostname:'pmx-dmz-fisico',      apps:['Proxmox VE DMZ'],                  authorizedUsers:['SGTIC'] },
];
